version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sklad
  
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    restart: always
    networks:
      - sklad
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:

networks:
  sklad:
